version: '3.9'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  app:
    build: .
    command: python app.py
    ports:
      - 5000:5000
    depends_on:
      - redis